In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
type(my_list)

list

In [5]:
my_arr = np.array(my_list) 

In [6]:
my_arr

array([1, 2, 3])

In [7]:
type(my_arr)

numpy.ndarray

In [8]:
# arange creates arrays of integer
arr = np.arange(0,10,2)

In [9]:
arr


array([0, 2, 4, 6, 8])

In [10]:
# Zeros & ones create arrays of floats 
np.zeros(shape = (10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(shape = (2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.random.seed(101)
arr1 = np.random.randint(0,100,10)


In [13]:
arr1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [14]:
# To get the maximum value in an array
arr1.max()

95

In [15]:
# To get the minimum value of an array
arr1.min()

9

In [16]:
# to get the index of the maximum value
arr1.argmax()

0

In [17]:
# To get the index of the minimum value
arr1.argmin()

7

In [18]:
# to get the average (mean) of all numbers in an array 
arr1.mean()

60.8

In [21]:
# To change the shape of an array
# reshape (x,y) --> no. of elements must be equal xy
arr1.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [25]:
mat = np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
# To make indexing 
# [no. of row , no. of column]
mat[8,5]

85

In [28]:
# to get every element in specific column
mat[: , 1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [29]:
# To get a slice of the data
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [30]:
# To change the value of this slice
mat[0:3,0:4]=4

In [31]:
mat

array([[ 4,  4,  4,  4,  4,  5,  6,  7,  8,  9],
       [ 4,  4,  4,  4, 14, 15, 16, 17, 18, 19],
       [ 4,  4,  4,  4, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])