In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('DATA/bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
# Target
labels =data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
# Features
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
len(X_train)

919

In [13]:
len(X)

1372

In [14]:
len(X_test)

453

In [17]:
# for scaling and normalizing the data
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)


In [23]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
model = Sequential()

# INPUT LAYER
model.add(Dense(4,input_dim = 4,activation = 'relu'))

# HIDDEN LAYER
model.add(Dense(8,activation='relu'))

#OUTPUT LAYER
model.add(Dense(1,activation='sigmoid'))

In [25]:
# COMPILING THE MODEL
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [27]:
# FITTING THE MODEL

model.fit(scaled_X_train,y_train,epochs = 100 , verbose = 2)

Epoch 1/100
 - 0s - loss: 0.1433 - acc: 0.9489
Epoch 2/100
 - 0s - loss: 0.1410 - acc: 0.9565
Epoch 3/100
 - 0s - loss: 0.1368 - acc: 0.9565
Epoch 4/100
 - 0s - loss: 0.1350 - acc: 0.9532
Epoch 5/100
 - 0s - loss: 0.1317 - acc: 0.9565
Epoch 6/100
 - 0s - loss: 0.1289 - acc: 0.9543
Epoch 7/100
 - 0s - loss: 0.1266 - acc: 0.9576
Epoch 8/100
 - 0s - loss: 0.1245 - acc: 0.9554
Epoch 9/100
 - 0s - loss: 0.1228 - acc: 0.9565
Epoch 10/100
 - 0s - loss: 0.1190 - acc: 0.9608
Epoch 11/100
 - 0s - loss: 0.1170 - acc: 0.9597
Epoch 12/100
 - 0s - loss: 0.1153 - acc: 0.9587
Epoch 13/100
 - 0s - loss: 0.1128 - acc: 0.9619
Epoch 14/100
 - 0s - loss: 0.1105 - acc: 0.9641
Epoch 15/100
 - 0s - loss: 0.1086 - acc: 0.9619
Epoch 16/100
 - 0s - loss: 0.1066 - acc: 0.9641
Epoch 17/100
 - 0s - loss: 0.1045 - acc: 0.9641
Epoch 18/100
 - 0s - loss: 0.1026 - acc: 0.9641
Epoch 19/100
 - 0s - loss: 0.1010 - acc: 0.9652
Epoch 20/100
 - 0s - loss: 0.0994 - acc: 0.9663
Epoch 21/100
 - 0s - loss: 0.0974 - acc: 0.9663
E

In [28]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [29]:
model.metrics_names

['loss', 'acc']

In [30]:
from sklearn.metrics import confusion_matrix , classification_report

In [31]:
predictions = model.predict_classes(scaled_X_test)


In [32]:
confusion_matrix(y_test,predictions)


array([[250,   7],
       [  2, 194]])

In [33]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.99      0.97      0.98       257
        1.0       0.97      0.99      0.98       196

avg / total       0.98      0.98      0.98       453



In [34]:
# TO SAVE THE MODEL

model.save('mysupermodel.h5')

In [35]:
# to Load the model

from keras.models import load_model

newmodel = load_model('mysupermodel.h5')

In [36]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    