In [1]:
import matplotlib.pyplot as plt
import cv2
%matplotlib inline

In [2]:
from keras.preprocessing.image import ImageDataGenerator

In [3]:
image_gen = ImageDataGenerator(rotation_range=30,
                              width_shift_range=0.1,
                              height_shift_range=0.1,
                              rescale=1/255,
                              shear_range=0.2,
                              zoom_range=0.2,
                              horizontal_flip=True,
                              fill_mode='nearest')

In [4]:
image_gen.flow_from_directory('dataset/train')

Found 8000 images belonging to 2 classes.


In [7]:
from keras.models import Sequential
from keras.layers import Activation,Dense , Dropout,Flatten,Conv2D,MaxPooling2D

In [9]:
model = Sequential()

model.add(Conv2D(filters=32 , kernel_size=(3,3),input_shape =(150,150,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(filters=64 , kernel_size=(3,3),input_shape =(150,150,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(filters=64 , kernel_size=(3,3),input_shape =(150,150,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(128))
model.add(Activation('relu'))

model.add(Dropout(0.5))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [10]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 148, 148, 32)      896       
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 34, 34, 64)        36928     
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 17, 17, 64)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 18496)             0         
__________

In [12]:
input_shape = (150,150,3)

In [13]:
batch_size = 16

training_img_gen = image_gen.flow_from_directory('dataset/train',
                                                target_size=input_shape[:2],
                                                batch_size=batch_size,
                                                class_mode='binary')

Found 8000 images belonging to 2 classes.


In [14]:

test_img_gen = image_gen.flow_from_directory('dataset/test',
                                                target_size=input_shape[:2],
                                                batch_size=batch_size,
                                                class_mode='binary')

Found 2000 images belonging to 2 classes.


In [15]:
training_img_gen.class_indices

{'CAT': 0, 'DOG': 1}

In [16]:
results = model.fit_generator(training_img_gen,epochs=1,steps_per_epoch = 150,
                             validation_data=test_img_gen,
                             validation_steps=12)

Epoch 1/1
150/150 [==============================] - 92s 614ms/step - loss: 0.6969 - acc: 0.5171 - val_loss: 0.6901 - val_acc: 0.5845


In [17]:
results.history['acc']

[0.5170833333333333]

In [18]:
from keras.models import load_model

In [19]:
new_model = load_model('cat_dog_100epochs.h5')

In [20]:
dog_file ='dataset/test/DOG/dog.4168.jpg' 

In [21]:
from keras.preprocessing import image

In [22]:
 dog_img = image.load_img(dog_file,target_size=(150,150))

In [23]:
dog_img = image.img_to_array(dog_img)

In [24]:
dog_img.shape

(150, 150, 3)

In [25]:
import numpy as np

In [26]:
dog_img = np.expand_dims(dog_img,axis=0)

In [27]:
dog_img.shape

(1, 150, 150, 3)

In [28]:
dog_img = dog_img/255

In [29]:
new_model.predict_classes(dog_img)

array([[1]], dtype=int32)

In [30]:
model.predict_classes(dog_img)

array([[1]], dtype=int32)

In [32]:
model.predict(dog_img)

array([[0.5105272]], dtype=float32)

In [33]:
new_model.predict(dog_img)

array([[0.79988647]], dtype=float32)